if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
	set(LT_LINUX ON)
	add_compile_definitions(LT_LINUX=1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Android")
	set(LT_ANDROID ON)
	add_compile_definitions(LT_ANDROID=1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
	set(LT_MAC ON)
	add_compile_definitions(LT_MAC=1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "iOS")
set(LT_IOS ON)
	add_compile_definitions(LT_IOS=1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
set(LT_WINDOWS ON)
	add_compile_definitions(LT_WINDOWS=1)
endif()