include_guard(GLOBAL)

set(LT_QT_CMAKE_PATH "C:/Qt/6.5.1/msvc2019_64/lib/cmake")

set(LT_SERVER_ADDR 101.43.32.170)
set(LT_SERVER_SVC_PORT 43898)
set(LT_SERVER_APP_PORT 44898)
set(LT_SERVER_USE_SSL OFF)
set(LT_RUN_AS_SERVICE OFF)
set(LT_WIN_SERVICE_NAME Lanthing)
set(LT_WIN_SERVICE_DISPLAY_NAME "Lanthing Service")
set(LT_TRANSPORT_TYPE ${LT_TRANSPORT_RTC})
set(LT_CRASH_ON_THREAD_HANGS ON)
set(LT_ENABLE_TEST ON)