add_compile_definitions(GL_SILENCE_DEPRECATION=1)

set(CMAKE_MACOSX_BUNDLE ON)
set(CMAKE_INSTALL_RPATH "@loader_path/../Frameworks")
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
set(CMAKE_OSX_ARCHITECTURES "arm64")

set(MACOSX_BUNDLE_BUNDLE_VERSION "${LT_VERSION_MAJOR}${LT_VERSION_MINOR}${LT_VERSION_PATCH}")
set(MACOSX_BUNDLE_GUI_IDENTIFIER net.lanthing)
set(MACOSX_BUNDLE_ICON_FILE lanthing.ico)