add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/tomlplusplus)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/utfcpp)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/amf)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/ffmpeg/${LT_PLAT})
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/breakpad_builder)
#add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/lodepng)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/sqlite/${LT_PLAT})

set(protobuf_MODULE_COMPATIBLE ON)
#protobuf依赖absl
find_package(absl REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/protobuf/${LT_THIRD_POSTFIX}/lib/cmake)
find_package(utf8_range REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/protobuf/${LT_THIRD_POSTFIX}/lib/cmake)
find_package(Protobuf REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/protobuf/${LT_THIRD_POSTFIX})
find_package(GTest REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/googletest/${LT_THIRD_POSTFIX})
find_package(g3log REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/g3log/${LT_THIRD_POSTFIX})
find_package(MbedTLS REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/mbedtls/${LT_THIRD_POSTFIX})
find_package(libuv REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/libuv/${LT_THIRD_POSTFIX})
find_package(SDL2 REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/sdl/${LT_THIRD_POSTFIX})
find_package(Opus REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/opus/${LT_THIRD_POSTFIX})

set(LT_LIBUV_TARGET)
if (TARGET uv_a)
    set(LT_LIBUV_TARGET uv_a)
elseif (TARGET uv)
    set(LT_LIBUV_TARGET uv)
elseif (TARGET libuv::uv_a)
    set(LT_LIBUV_TARGET libuv::uv_a)
elseif (TARGET libuv::uv)
    set(LT_LIBUV_TARGET libuv::uv)
else()
    set(LT_LIBUV_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/third_party/prebuilt/libuv/${LT_THIRD_POSTFIX})
    if (LT_WINDOWS)
        if (EXISTS ${LT_LIBUV_ROOT}/lib/uv_a.lib)
            set(LT_LIBUV_LIBRARY ${LT_LIBUV_ROOT}/lib/uv_a.lib)
        elseif (EXISTS ${LT_LIBUV_ROOT}/lib/uv.lib)
            set(LT_LIBUV_LIBRARY ${LT_LIBUV_ROOT}/lib/uv.lib)
        endif()
    else()
        if (EXISTS ${LT_LIBUV_ROOT}/lib/libuv_a.a)
            set(LT_LIBUV_LIBRARY ${LT_LIBUV_ROOT}/lib/libuv_a.a)
        elseif (EXISTS ${LT_LIBUV_ROOT}/lib/libuv.a)
            set(LT_LIBUV_LIBRARY ${LT_LIBUV_ROOT}/lib/libuv.a)
        endif()
    endif()

    if (LT_LIBUV_LIBRARY)
        add_library(lt_libuv_fallback STATIC IMPORTED GLOBAL)
        set_target_properties(lt_libuv_fallback PROPERTIES
            IMPORTED_LOCATION ${LT_LIBUV_LIBRARY}
            INTERFACE_INCLUDE_DIRECTORIES ${LT_LIBUV_ROOT}/include
        )
        set(LT_LIBUV_TARGET lt_libuv_fallback)
    else()
        message(FATAL_ERROR "libuv target not found and fallback library missing under ${LT_LIBUV_ROOT}")
    endif()
endif()

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/imgui_builder)

add_subdirectory(ltproto)
add_subdirectory(src/transport)

#Qt
list(APPEND CMAKE_PREFIX_PATH ${LT_QT_CMAKE_PATH})
set(CMAKE_AUTORCC ON)
find_package(Qt6 REQUIRED COMPONENTS Widgets Gui LinguistTools)
qt_standard_project_setup()
get_target_property(_qmake_executable Qt6::qmake IMPORTED_LOCATION)
get_filename_component(_qt_bin_dir "${_qmake_executable}" DIRECTORY)
find_program(WINDEPLOYQT_EXECUTABLE windeployqt HINTS "${_qt_bin_dir}")
find_program(MACDEPLOYQT_EXECUTABLE macdeployqt HINTS "${_qt_bin_dir}")

if(LT_WINDOWS)
    include(${CMAKE_CURRENT_LIST_DIR}/windows.cmake)
elseif (LT_LINUX)
    include(${CMAKE_CURRENT_LIST_DIR}/linux.cmake)
elseif(LT_MAC)
    include(${CMAKE_CURRENT_LIST_DIR}/mac.cmake)
endif()