find_package(VPL REQUIRED PATHS third_party/prebuilt/onevpl/${LT_THIRD_POSTFIX})
find_package(PkgConfig REQUIRED)
pkg_check_modules(GLib REQUIRED IMPORTED_TARGET GLOBAL glib-2.0)
pkg_check_modules(X11 REQUIRED IMPORTED_TARGET GLOBAL x11)
pkg_check_modules(Va REQUIRED IMPORTED_TARGET GLOBAL libva)
pkg_check_modules(Va-X11 REQUIRED IMPORTED_TARGET GLOBAL libva-x11)
pkg_check_modules(Va-Wayland REQUIRED IMPORTED_TARGET GLOBAL libva-wayland)
pkg_check_modules(Drm REQUIRED IMPORTED_TARGET GLOBAL libdrm)
pkg_check_modules(Va-Drm REQUIRED IMPORTED_TARGET GLOBAL libva-drm)
pkg_check_modules(GL REQUIRED IMPORTED_TARGET GLOBAL gl)
pkg_check_modules(GLES REQUIRED IMPORTED_TARGET GLOBAL glesv2)
pkg_check_modules(EGL REQUIRED IMPORTED_TARGET GLOBAL egl)
pkg_check_modules(MFX REQUIRED IMPORTED_TARGET GLOBAL libmfx)