find_package(VPL REQUIRED PATHS third_party/prebuilt/onevpl/${LT_THIRD_POSTFIX})
find_package(PkgConfig REQUIRED)
    pkg_check_modules(GLib REQUIRED IMPORTED_TARGET glib-2.0)
    pkg_check_modules(X11 REQUIRED IMPORTED_TARGET x11)
    pkg_check_modules(Va REQUIRED IMPORTED_TARGET libva)
    pkg_check_modules(Drm REQUIRED IMPORTED_TARGET libdrm)
    pkg_check_modules(Va-Drm REQUIRED IMPORTED_TARGET libva-drm)
    pkg_check_modules(GL REQUIRED IMPORTED_TARGET gl)
    pkg_check_modules(GLES REQUIRED IMPORTED_TARGET glesv2)
    pkg_check_modules(EGL REQUIRED IMPORTED_TARGET egl)
    pkg_check_modules(MFX REQUIRED IMPORTED_TARGET libmfx)