name: win-package
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout
        with:
          submodules: true
        uses: actions/checkout@v4
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
      - name: Fetch prebuilt
        run: ./build.ps1 prebuilt fetch
      - name: Build lanthing-pc
        run: ./build.ps1 build Release
      - name: Generate Zip
        run: |
          echo ${{ github.sha }} > Release.txt
          $OP = "${{ github.workspace }}/install/RelWithDebInfo/bin"
          $PDB = "${{ github.workspace }}/install/RelWithDebInfo/pdb"
          Compress-Archive -Path Release.txt,LICENSE,third-party-licenses.txt,$OP/platforms,$OP/styles,$OP/abseil_dll.dll,$OP/app.exe,$OP/avcodec-59.dll,$OP/avutil-57.dll,$OP/breakpad.dll,$OP/g3log.dll,$OP/lanthing.exe,$OP/libprotobuf-lite.dll,$OP/libvpl.dll,$OP/ltlib.dll,$OP/Qt6Core.dll,$OP/Qt6Gui.dll,$OP/Qt6Widgets.dll,$OP/rtc.dll,$OP/rtc2.dll,$OP/sdl2.dll,$OP/sqlite3.dll,$OP/uv.dll -DestinationPath lanthing.${{ github.ref_name }}.zip
          Compress-Archive -Path Release.txt,$PDB -DestinationPath pdb.${{ github.ref_name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lanthing.${{ github.ref_name }}.zip
            pdb.${{ github.ref_name }}.zip
