name: win-build
on:
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        with:
          submodules: true
        uses: actions/checkout@v4
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
      - name: Fetch prebuilt
        run: ./build.ps1 prebuilt fetch
      - name: Build lanthing-pc
        run: ./build.ps1 build Release
      - name: Run Tests
        run: |
          $Env:PATH = "${{ github.workspace }}/install/RelWithDebInfo/bin;$Env:PATH"
          cd ./build/RelWithDebInfo
          ctest -C RelWithDebInfo -V